// Static product data - used as fallback when Supabase database is unavailable
// Replace this with live data by updating .env with correct Supabase credentials

export const staticCategories = [
    {
        id: 1,
        name_en: "Basmati Rice",
        name_ur: "باسمتی چاول",
        slug: "basmati-rice",
        segment: "AGRI",
        description: "Premium long-grain Basmati rice varieties known for their aroma and taste.",
        image: null,
    },
    {
        id: 2,
        name_en: "Non-Basmati Rice",
        name_ur: "چاول",
        slug: "non-basmati-rice",
        segment: "AGRI",
        description: "Quality non-Basmati rice varieties for diverse culinary applications.",
        image: null,
    },
    {
        id: 3,
        name_en: "Spices",
        name_ur: "مصالحے",
        slug: "spices",
        segment: "AGRI",
        description: "Authentic whole and ground spices sourced from the finest farms.",
        image: null,
    },
    {
        id: 4,
        name_en: "Bedding & Bed Linen",
        name_ur: "بستر اور چادریں",
        slug: "bedding",
        segment: "TEXTILE",
        description: "Premium quality bedding including sheets, duvet covers, and pillowcases.",
        image: null,
    },
    {
        id: 5,
        name_en: "Bath & Towels",
        name_ur: "غسل اور تولیے",
        slug: "bath-towels",
        segment: "TEXTILE",
        description: "Luxurious towels and bath accessories for hospitality and retail.",
        image: null,
    },
    {
        id: 6,
        name_en: "Kitchen & Institutional",
        name_ur: "ادارہ جاتی ٹیکسٹائل",
        slug: "kitchen-institutional",
        segment: "TEXTILE",
        description: "Durable kitchen linens and institutional textiles for commercial use.",
        image: null,
    },
];

export const staticProducts = [
    {
        id: 1,
        name_en: "1121 Basmati Rice",
        name_ur: "1121 باسمتی چاول",
        slug: "1121-basmati-rice",
        category: "AGRI",
        subcategory: "Basmati Rice",
        short_description: "Premium extra long grain Basmati rice with exceptional aroma and taste. Ideal for biryani and pulao.",
        long_description: "Our 1121 Basmati Rice is the finest extra-long grain variety, celebrated worldwide for its superior aroma, elongation, and taste. Each grain elongates up to 8.4mm after cooking, making it the preferred choice for premium dishes like biryani and pulao.",
        featured: true,
        images: "[]",
        tags: '["Extra Long Grain", "Premium", "Aromatic"]',
        variants: '[{"type": "Sella (Parboiled)", "packing": ["5kg", "10kg", "25kg", "50kg"]}, {"type": "Steam (White)", "packing": ["5kg", "10kg", "25kg"]}, {"type": "Raw/Creamy", "packing": ["10kg", "25kg", "50kg"]}]',
        price_example: "FOB Karachi: $850-1100/MT",
    },
    {
        id: 2,
        name_en: "Super Kernel Basmati",
        name_ur: "سپر کرنل باسمتی",
        slug: "super-kernel-basmati",
        category: "AGRI",
        subcategory: "Basmati Rice",
        short_description: "Long grain basmati rice with natural aroma, perfect for everyday premium cooking.",
        long_description: "Super Kernel Basmati Rice is a highly sought-after variety known for its long grains, natural fragrance, and excellent cooking properties.",
        featured: true,
        images: "[]",
        tags: '["Long Grain", "Natural Aroma", "Versatile"]',
        variants: '[{"type": "Sella (Parboiled)", "packing": ["5kg", "10kg", "25kg"]}, {"type": "Steam (White)", "packing": ["5kg", "10kg", "25kg", "50kg"]}]',
        price_example: "FOB Karachi: $700-950/MT",
    },
    {
        id: 3,
        name_en: "PK 386 Basmati",
        name_ur: "PK 386 باسمتی",
        slug: "pk-386-basmati",
        category: "AGRI",
        subcategory: "Basmati Rice",
        short_description: "Traditional Pakistani Basmati rice variety with excellent elongation and taste profile.",
        long_description: "PK 386 is a traditional Pakistani Basmati rice variety that combines excellent elongation with a distinctive taste profile.",
        featured: false,
        images: "[]",
        tags: '["Traditional", "Good Elongation", "Authentic"]',
        variants: '[{"type": "Sella", "packing": ["25kg", "50kg"]}, {"type": "Steam", "packing": ["25kg", "50kg"]}]',
        price_example: "FOB Karachi: $600-800/MT",
    },
    {
        id: 4,
        name_en: "IRRI-6 Long Grain Rice",
        name_ur: "IRRI-6 چاول",
        slug: "irri-6-long-grain",
        category: "AGRI",
        subcategory: "Non-Basmati Rice",
        short_description: "Versatile long grain non-Basmati rice, popular for everyday meals across global markets.",
        long_description: "IRRI-6 Long Grain Rice is one of the most exported non-Basmati varieties from Pakistan. Known for its versatility and consistent quality, it serves as a staple in many countries.",
        featured: true,
        images: "[]",
        tags: '["Long Grain", "Versatile", "High Volume"]',
        variants: '[{"type": "Parboiled", "packing": ["25kg", "50kg"]}, {"type": "White (5% Broken)", "packing": ["25kg", "50kg"]}, {"type": "White (15% Broken)", "packing": ["50kg"]}]',
        price_example: "FOB Karachi: $400-550/MT",
    },
    {
        id: 5,
        name_en: "Turmeric Powder",
        name_ur: "ہلدی",
        slug: "turmeric-powder",
        category: "AGRI",
        subcategory: "Spices",
        short_description: "Pure ground turmeric with high curcumin content, rich golden color and earthy flavor.",
        long_description: "Our Turmeric Powder is sourced from premium quality turmeric fingers and processed to retain maximum curcumin content. Known for its vibrant golden color, earthy aroma, and numerous health benefits.",
        featured: true,
        images: "[]",
        tags: '["Ground Spice", "High Curcumin", "Pure"]',
        variants: '[{"type": "Powder", "packing": ["100g", "250g", "500g", "1kg", "25kg"]}]',
        price_example: "FOB Karachi: $1200-1800/MT",
    },
    {
        id: 6,
        name_en: "Red Chili Powder",
        name_ur: "لال مرچ",
        slug: "red-chili-powder",
        category: "AGRI",
        subcategory: "Spices",
        short_description: "Premium quality red chili powder with vibrant color and balanced heat level.",
        long_description: "Our Red Chili Powder is made from carefully selected red chilies, dried and ground to perfection. It delivers a vibrant red color, characteristic aroma, and well-balanced heat.",
        featured: false,
        images: "[]",
        tags: '["Ground Spice", "Vibrant Color", "Balanced Heat"]',
        variants: '[{"type": "Powder (Mild)", "packing": ["100g", "500g", "25kg"]}, {"type": "Powder (Hot)", "packing": ["100g", "500g", "25kg"]}]',
        price_example: "FOB Karachi: $1000-1500/MT",
    },
    {
        id: 7,
        name_en: "Premium Bed Sheet Set",
        name_ur: "بیڈ شیٹ سیٹ",
        slug: "premium-bed-sheet-set",
        category: "TEXTILE",
        subcategory: "Bedding & Bed Linen",
        short_description: "High thread count cotton bed sheet sets in various sizes and designs.",
        long_description: "Our Premium Bed Sheet Sets are crafted from the finest Pakistani cotton, known worldwide for its superior quality. Each set includes fitted sheet, flat sheet, and pillowcases.",
        featured: true,
        images: "[]",
        tags: '["100% Cotton", "High Thread Count", "Durable"]',
        variants: '[{"type": "200TC", "packing": ["Single", "Double", "Queen", "King"]}, {"type": "400TC Sateen", "packing": ["Queen", "King"]}, {"type": "600TC Luxury", "packing": ["Queen", "King"]}]',
        price_example: "$8-25/set (200-600TC)",
    },
    {
        id: 8,
        name_en: "Egyptian Cotton Towels",
        name_ur: "تولیے",
        slug: "egyptian-cotton-towels",
        category: "TEXTILE",
        subcategory: "Bath & Towels",
        short_description: "Luxurious cotton towels with excellent absorbency, ideal for hospitality and retail.",
        long_description: "Our Egyptian Cotton Towels are manufactured using premium long-staple cotton fibers, ensuring exceptional softness, absorbency, and durability. Perfect for luxury hotels, spas, and premium retail markets.",
        featured: true,
        images: "[]",
        tags: '["Premium Cotton", "Highly Absorbent", "Durable"]',
        variants: '[{"type": "Bath Towel (600gsm)", "packing": ["Individual", "Sets of 4", "Bulk (50pcs)"]}, {"type": "Hand Towel (500gsm)", "packing": ["Individual", "Sets of 6"]}, {"type": "Washcloth (450gsm)", "packing": ["Sets of 6", "Bulk (100pcs)"]}]',
        price_example: "$3-12/piece",
    },
    {
        id: 9,
        name_en: "Kitchen Aprons & Linens",
        name_ur: "کچن لینن",
        slug: "kitchen-aprons-linens",
        category: "TEXTILE",
        subcategory: "Kitchen & Institutional",
        short_description: "Durable kitchen textiles including aprons, oven mitts, and tea towels.",
        long_description: "Our kitchen linen range includes professionally designed aprons, oven mitts, pot holders, and tea towels. Made from durable cotton and cotton-blend fabrics.",
        featured: false,
        images: "[]",
        tags: '["Commercial Grade", "Cotton Blend", "Custom Branding"]',
        variants: '[{"type": "Chef Apron", "packing": ["Individual", "Bulk (25pcs)"]}, {"type": "Tea Towel Set", "packing": ["Sets of 3", "Bulk (50pcs)"]}, {"type": "Oven Mitt Pair", "packing": ["Pairs", "Bulk (25 pairs)"]}]',
        price_example: "$2-8/piece",
    },
    {
        id: 10,
        name_en: "Duvet Covers",
        name_ur: "لحاف کور",
        slug: "duvet-covers",
        category: "TEXTILE",
        subcategory: "Bedding & Bed Linen",
        short_description: "Elegant duvet covers in premium cotton with contemporary and classic designs.",
        long_description: "Our Duvet Covers are crafted from premium Pakistani cotton, providing exceptional comfort and durability. Available in a variety of styles from minimalist modern to classic patterns.",
        featured: true,
        images: "[]",
        tags: '["100% Cotton", "Custom Designs", "Premium Quality"]',
        variants: '[{"type": "200TC Percale", "packing": ["Queen", "King"]}, {"type": "400TC Sateen", "packing": ["Queen", "King", "Super King"]}]',
        price_example: "$12-30/piece",
    },
];
